[build]
  publish = "docs" # Cambia esto si los archivos HTML están en otra carpeta.
  command = "" # Deja vacío si no necesitas construir nada.

[[redirects]]
  from = "/ads.txt"
  to = "/ads.txt"
  status = 200
