[build]
  # Ya que tu sitio es estático, no necesitas comando de build
  command = ""
  # Publica todo lo que esté dentro de la carpeta 'docs'
  publish = "docs"

[[redirects]]
  from = "/ads.txt"
  to   = "/ads.txt"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
