[build]
  publish = "docs" # Cambia esto si "docs" no es la carpeta que contiene los archivos del sitio.
  command = "" # Déjalo vacío si no necesitas un proceso de construcción.

[[redirects]]
  from = "/ads.txt"
  to = "/ads.txt"
  status = 200
